platform :ios, '8.0'
target 'IOSYueQiProject' do
pod 'AFNetworking', '~> 3.0.4'
pod 'SDWebImage', '~> 3.8.1'
pod 'UMengSocialCOM', '~> 5.2.1'
pod 'FMDB', '~> 2.6'
pod 'HyphenateFullSDK'
pod 'QBImagePickerController', '~> 3.4.0'
pod 'Masonry', '~> 0.6.2'
pod 'MJExtension', '~> 3.0.11' 
end
